### ISSUE TITLE
Load daily visitors as time series

### ISSUE THREAD

**Issue by ghost** [kanaku/ROptimizely#2]
Hi,

first of all thank you for making my work with Optimizely a bit easier. However, I would like to know whether you plan to include the possibility to load daily data as a time series with its corresponding variations, goals and metrics etc? According to the current status, your focus exclusively on the results rather than on the way to them.

Thx
Eugene

**Comment by keerthichandra** [comment]
Hi Eugene, 
Optimizely doesn't support/provide  daily time series information or any raw data for that matter. I had same thought and the only solution I can think about is extract data daily(or any window) with time stamp to get a time series. 

If Optimizely provides this data stream, I will incorporate this feature into the package. 

Thanks,
KC
